/**
 * Libellés et jeux d'icônes du constructeur.
 *
 * Séparés des composants : ce sont des données, elles doublaient la longueur
 * du fichier de l'éditeur et n'ont aucune logique de rendu.
 */

import {
  Image,
  LayoutGrid,
  MapPin,
  MessageCircleQuestionMark,
  Phone,
  Search,
  Star,
  Tags,
  Video,
  CalendarClock,
  GalleryHorizontal,
  BadgePercent,
} from 'lucide-react'
import { type BlockStyle } from '@/lib/clyde/types'

export const BLOCK_STYLE_PRESETS: Array<{
  id: string
  label: { fr: string; en: string }
  hint: { fr: string; en: string }
  style: BlockStyle
}> = [
  { id: 'restaurant', label: { fr: 'Restaurant', en: 'Restaurant' }, hint: { fr: 'Généreux et lisible', en: 'Generous and readable' }, style: { align: 'left', fontScale: 1.1, fontWeight: 700, paddingY: 40, paddingX: 24, radius: 'round' } },
  { id: 'boutique', label: { fr: 'Boutique', en: 'Shop' }, hint: { fr: 'Net et élégant', en: 'Clean and elegant' }, style: { align: 'center', fontScale: 1, fontWeight: 600, paddingY: 32, paddingX: 20, radius: 'soft' } },
  { id: 'service', label: { fr: 'Service', en: 'Service' }, hint: { fr: 'Direct et rassurant', en: 'Direct and reassuring' }, style: { align: 'left', fontScale: 0.95, fontWeight: 500, paddingY: 28, paddingX: 20, radius: 'soft' } },
  { id: 'createur', label: { fr: 'Créateur', en: 'Creator' }, hint: { fr: 'Fort et éditorial', en: 'Bold and editorial' }, style: { align: 'center', fontScale: 1.2, fontWeight: 700, paddingY: 48, paddingX: 24, radius: 'sharp' } },
]

export const ICONS = {
  Image,
  Search,
  Tags,
  LayoutGrid,
  GalleryHorizontal,
  BadgePercent,
  CalendarClock,
  Star,
  MessageCircleQuestionMark,
  MapPin,
  Video,
  Phone,
} as const

/** Le jeu de libellés d'une langue, tel que le reçoivent les panneaux. */
export type Copy = (typeof LABELS)[keyof typeof LABELS]

export const LABELS = {
  fr: {
    title: 'Éditer ma page',
    description: 'Construisez votre page publique, puis vérifiez-la en direct.',
    preview: 'Aperçu en direct',
    previewDesktop: 'Aperçu ordinateur',
    previewMobile: 'Aperçu mobile',
    structure: 'Structure',
    settings: 'Réglages du bloc',
    /* Libellé court réservé à la barre du téléphone : « Réglages du bloc » y
       tient sur deux lignes face à « Structure » sur une seule, ce qui déséquilibre
       les deux moitiés. L'en-tête du tiroir, lui, garde le libellé entier — c'est
       là qu'il faut dire de quoi on règle les propriétés. */
    settingsShort: 'Réglages',
    addBlock: 'Ajouter un bloc',
    visible: 'Visible sur ma page',
    hidden: 'Masqué',
    moveUp: 'Monter',
    moveDown: 'Descendre',
    duplicate: 'Dupliquer',
    duplicateUnavailable: 'Ce bloc ne peut apparaître qu’une fois',
    delete: 'Supprimer',
    deleted: 'Bloc supprimé',
    restore: 'Rétablir',
    movedTo: 'déplacé en position',
    of: 'sur',
    noSelection: 'Style de la page',
    pageStyle: 'Style de la page',
    pageStyleHint: 'Fond, couleurs et identité de toute la page',
    pageGenre: 'Genre de la page',
    pageGenreHint: 'Deux façons de présenter la même page : le contenu ne change pas, seule la mise en scène change.',
    genreVitrine: 'Vitrine',
    genreVitrineDesc: 'Page magazine : couverture, sections aérées, pour se présenter.',
    genreCommande: 'Commande rapide',
    genreCommandeDesc: 'Façon appli de livraison : rayons à gauche, liste dense, pour commander vite.',
    ambiance: 'Ambiance de la page',
    ambianceHint: 'Une ambiance règle d’un coup le fond de la page, le texte et la couleur des boutons. Chaque bloc suit automatiquement — sauf si vous lui donnez ses propres couleurs.',
    pageColors: 'Couleurs de la page',
    pageBackground: 'Fond de la page',
    pageInk: 'Texte',
    pageBrand: 'Boutons & accents',
    resetColors: 'Revenir aux couleurs de la page',
    resetStyle: 'Réinitialiser toute l’apparence',
    resetStyleHint: 'Retrouver les réglages par défaut de ce bloc',
    customColorsOn: 'Ce bloc a ses propres couleurs.',
    contentSection: 'Contenu',
    style: 'Apparence',
    typography: 'Typographie',
    alignment: 'Alignement',
    left: 'Gauche',
    center: 'Centre',
    right: 'Droite',
    scale: 'Taille du texte',
    weight: 'Graisse',
    colors: 'Couleurs',
    background: 'Fond du bloc',
    textColor: 'Couleur du texte',
    brandColor: 'Couleur de marque',
    spacing: 'Espacement',
    vertical: 'Vertical',
    horizontal: 'Horizontal',
    radius: 'Angles',
    sharp: 'Carré',
    soft: 'Doux',
    round: 'Rond',
    hero: 'Couverture',
    titleField: 'Titre',
    subtitle: 'Sous-titre',
    cta: 'Libellé du bouton',
    imageUrl: 'URL de l’image',
    variant: 'Position du contenu',
    height: 'Hauteur',
    overlay: 'Voile sombre',
    ctaTarget: 'Le bouton mène à',
    ctaCatalogue: 'Le catalogue',
    ctaBooking: 'Les réservations',
    ctaContact: 'WhatsApp',
    heroLogo: 'Logo dans la couverture',
    heroLogoSize: 'Taille',
    heroLogoAlign: 'Position',
    sizeS: 'Petit',
    sizeM: 'Moyen',
    sizeL: 'Grand',
    alignLeft: 'Gauche',
    alignCenter: 'Centre',
    alignRight: 'Droite',
    heroLogoHint: 'Sans image, le logo de la boutique est utilisé.',
    catalogue: 'Catalogue',
    catalogueTitle: 'Titre de section',
    display: 'Affichage',
    grid: 'Grille',
    list: 'Liste',
    columns: 'Colonnes',
    showPrice: 'Afficher les prix',
    showRating: 'Afficher les avis',
    actionLabel: 'Action produit',
    categories: 'Catégories',
    autoCategories: 'Générer depuis le catalogue',
    categoryItems: 'Catégories manuelles',
    categoryHint: 'Une catégorie par ligne.',
    categoryDisplay: 'Affichage',
    categoryWrap: 'Pastilles sur plusieurs lignes',
    categoryScroll: 'Une ligne qui glisse',
    categoryCard: 'Vignettes illustrées',
    booking: 'Réservation',
    bookingDays: 'Jours ouverts à la réservation',
    hours: 'Horaires & localisation',
    address: 'Adresse',
    mapQuery: 'Recherche de carte',
    contact: 'Contact',
    phone: 'Téléphone',
    email: 'Email',
    descriptionField: 'Description',
    publicPage: 'Ouvrir ma page',
  undo: 'Annuler',
  redo: 'Rétablir',
  readiness: 'Votre page est prête à',
  readinessDone: 'Votre page est complète.',
    empty: 'Ajoutez un bloc pour commencer.',
    demoTitle: 'Explorer le constructeur de page',
    demoDescription: 'Connectez-vous en mode démo pour inspecter les blocs, les réglages et la preview live.',
    demoButton: 'Entrer dans la démo',
  },
  en: {
    title: 'Edit my page',
    description: 'Build your public page, then check it live as you edit.',
    preview: 'Live preview',
    previewDesktop: 'Desktop preview',
    previewMobile: 'Mobile preview',
    structure: 'Structure',
    settings: 'Block settings',
    settingsShort: 'Settings',
    addBlock: 'Add a block',
    visible: 'Visible on my page',
    hidden: 'Hidden',
    moveUp: 'Move up',
    moveDown: 'Move down',
    duplicate: 'Duplicate',
    duplicateUnavailable: 'This block can only appear once',
    delete: 'Delete',
    deleted: 'Block deleted',
    restore: 'Restore',
    movedTo: 'moved to position',
    of: 'of',
    noSelection: 'Page style',
    pageStyle: 'Page style',
    pageStyleHint: 'Background, colors, and identity of the whole page',
    pageGenre: 'Page genre',
    pageGenreHint: 'Two ways to present the same page: content stays, only the staging changes.',
    genreVitrine: 'Showcase',
    genreVitrineDesc: 'Magazine page: cover, airy sections, made to present yourself.',
    genreCommande: 'Quick order',
    genreCommandeDesc: 'Delivery-app style: aisles on the left, dense list, made to order fast.',
    ambiance: 'Page mood',
    ambianceHint: 'A mood sets the page background, text, and button color at once. Every block follows automatically — unless you give it its own colors.',
    pageColors: 'Page colors',
    pageBackground: 'Page background',
    pageInk: 'Text',
    pageBrand: 'Buttons & accents',
    resetColors: 'Back to page colors',
    resetStyle: 'Reset all appearance',
    resetStyleHint: 'Restore this block’s default settings',
    customColorsOn: 'This block has its own colors.',
    contentSection: 'Content',
    style: 'Appearance',
    typography: 'Typography',
    alignment: 'Alignment',
    left: 'Left',
    center: 'Center',
    right: 'Right',
    scale: 'Text size',
    weight: 'Weight',
    colors: 'Colors',
    background: 'Block background',
    textColor: 'Text color',
    brandColor: 'Brand color',
    spacing: 'Spacing',
    vertical: 'Vertical',
    horizontal: 'Horizontal',
    radius: 'Corners',
    sharp: 'Sharp',
    soft: 'Soft',
    round: 'Round',
    hero: 'Cover',
    titleField: 'Title',
    subtitle: 'Subtitle',
    cta: 'Button label',
    imageUrl: 'Image URL',
    variant: 'Content position',
    height: 'Height',
    overlay: 'Dark overlay',
    ctaTarget: 'Button goes to',
    ctaCatalogue: 'The catalog',
    ctaBooking: 'Bookings',
    ctaContact: 'WhatsApp',
    heroLogo: 'Logo on the cover',
    heroLogoSize: 'Size',
    heroLogoAlign: 'Position',
    sizeS: 'Small',
    sizeM: 'Medium',
    sizeL: 'Large',
    alignLeft: 'Left',
    alignCenter: 'Center',
    alignRight: 'Right',
    heroLogoHint: 'Without an image, the shop logo is used.',
    catalogue: 'Catalog',
    catalogueTitle: 'Section title',
    display: 'Display',
    grid: 'Grid',
    list: 'List',
    columns: 'Columns',
    showPrice: 'Show prices',
    showRating: 'Show ratings',
    actionLabel: 'Product action',
    categories: 'Categories',
    autoCategories: 'Generate from catalog',
    categoryItems: 'Manual categories',
    categoryHint: 'One category per line.',
    categoryDisplay: 'Display',
    categoryWrap: 'Chips on several lines',
    categoryScroll: 'Single sliding row',
    categoryCard: 'Illustrated tiles',
    booking: 'Booking',
    bookingDays: 'Days open for booking',
    hours: 'Hours & location',
    address: 'Address',
    mapQuery: 'Map search',
    contact: 'Contact',
    phone: 'Phone',
    email: 'Email',
    descriptionField: 'Description',
    publicPage: 'Open my page',
  undo: 'Undo',
  redo: 'Redo',
  readiness: 'Your page is',
  readinessDone: 'Your page is complete.',
    empty: 'Add a block to get started.',
    demoTitle: 'Explore the Page Builder',
    demoDescription: 'Use demo mode to inspect blocks, settings, and the live preview before connecting your account.',
    demoButton: 'Enter demo mode',
  },
} as const
